package com.tenderlitch.entity.demo;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.tenderlitch.core.entity.AbstractEntity;
public class UserDemo extends AbstractEntity {
	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.NAME
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String name;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.PIN
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String pin;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.PASSWORD
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String password;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.GENDER
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String gender;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.STATE
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private Short state;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.PHONE1
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String phone1;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.PHONE2
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String phone2;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.EMAIL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String email;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MES_USER.TEL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	private String tel;
	private String userPost;
	
	/** 鐧婚檰鐝粍 */
	private String loginGroup;
	

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.NAME
	 *
	 * @return the value of MES_USER.NAME
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.NAME
	 *
	 * @param name the value for MES_USER.NAME
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.PIN
	 *
	 * @return the value of MES_USER.PIN
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getPin() {
		return pin;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.PIN
	 *
	 * @param pin the value for MES_USER.PIN
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setPin(String pin) {
		this.pin = pin;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.PASSWORD
	 *
	 * @return the value of MES_USER.PASSWORD
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.PASSWORD
	 *
	 * @param password the value for MES_USER.PASSWORD
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.GENDER
	 *
	 * @return the value of MES_USER.GENDER
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.GENDER
	 *
	 * @param gender the value for MES_USER.GENDER
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.STATE
	 *
	 * @return the value of MES_USER.STATE
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public Short getState() {
		return state;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.STATE
	 *
	 * @param state the value for MES_USER.STATE
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setState(Short state) {
		this.state = state;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.PHONE1
	 *
	 * @return the value of MES_USER.PHONE1
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getPhone1() {
		return phone1;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.PHONE1
	 *
	 * @param phone1 the value for MES_USER.PHONE1
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.PHONE2
	 *
	 * @return the value of MES_USER.PHONE2
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getPhone2() {
		return phone2;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.PHONE2
	 *
	 * @param phone2 the value for MES_USER.PHONE2
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.EMAIL
	 *
	 * @return the value of MES_USER.EMAIL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.EMAIL
	 *
	 * @param email the value for MES_USER.EMAIL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MES_USER.TEL
	 *
	 * @return the value of MES_USER.TEL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MES_USER.TEL
	 *
	 * @param tel the value for MES_USER.TEL
	 *
	 * @abatorgenerated Mon Jun 16 11:02:14 CST 2008
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}


	/**
	 * equals鏂规硶澶嶅啓
	 */
	public boolean equals(Object o) {
		if (!(o instanceof UserDemo)) {
			return false;
		}
		UserDemo user = (UserDemo) o;
		return new EqualsBuilder().append(this.getPin(), user.getPin()).isEquals();
	}

	/**
	 * hashCode鏂规硶澶嶅啓
	 */
	public int hashCode() {
		return new HashCodeBuilder(61, 15).append(this.getPin()).toHashCode();
	}

	/**
	 * @return the loginGroup
	 */
	public String getLoginGroup() {
		return loginGroup;
	}

	/**
	 * @param loginGroup the loginGroup to set
	 */
	public void setLoginGroup(String loginGroup) {
		this.loginGroup = loginGroup;
	}

	public String getUserPost() {
		return userPost;
	}

	public void setUserPost(String userPost) {
		this.userPost = userPost;
	}
}















